# Generated by Django 4.2 on 2024-07-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicule', '0005_vehicule_couleur_alter_vehicule_photo'),
        ('Client', '0002_remove_client_code_postal_remove_client_num_permis_and_more'),
        ('Conducteur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signature', models.DateField()),
                ('duree_contrat', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conditions', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.client')),
                ('conducteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conducteur.conducteur')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicule.vehicule')),
            ],
        ),
    ]
