# Generated by Django 4.2 on 2024-07-16 10:33


from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('Contrat', '0002_contrat_date_debut_contrat_contrat_date_fin_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='date_debut_contrat',
            field=models.DateField(default=None),  # Change default to None or a valid date string
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_fin_contrat',
            field=models.DateField(default=None),  # Change default to None or a valid date string
            preserve_default=False,
        ),
    ]