# Generated by Django 4.2 on 2024-07-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contrat', '0003_alter_contrat_date_debut_contrat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrat',
            old_name='date_debut_contrat',
            new_name='date_prise',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='conditions',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='contrat',
            old_name='montant_total',
            new_name='total_ttc',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='date_fin_contrat',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='date_signature',
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='duree_contrat',
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_retour',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='contrat',
            name='reste',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='restitution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
