# Generated by Django 4.2 on 2024-07-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conducteur', '0001_initial'),
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='client',
            name='num_permis',
        ),
        migrations.RemoveField(
            model_name='client',
            name='ville',
        ),
        migrations.AddField(
            model_name='client',
            name='conducteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Conducteur.conducteur'),
        ),
        migrations.AddField(
            model_name='client',
            name='est_conducteur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='informations_paiement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
