# Generated by Django 4.2 on 2024-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_client_code_postal_remove_client_num_permis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Mademoiselle', 'Mademoiselle'), ('Madame', 'Madame'), ('Monsieur', 'Monsieur')], default='Monsieur', max_length=200, null=True),
        ),
    ]
