# Generated by Django 4.2 on 2024-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_client_lieu_naissance_client_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
