# Generated by Django 4.2 on 2024-08-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_remove_client_informations_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nom_complet',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
