# Generated by Django 4.2 on 2024-07-11 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contrat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Contrat.contrat')),
            ],
        ),
    ]
