# Generated by Django 4.2 on 2024-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('immatriculation', models.CharField(max_length=20)),
            ],
        ),
    ]
