# Generated by Django 4.2 on 2024-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicule', '0002_vehicule_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos'),
        ),
    ]
