# Generated by Django 4.2 on 2024-07-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicule', '0003_alter_vehicule_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='immatriculation',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
