# Generated by Django 4.2 on 2024-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicule', '0004_alter_vehicule_immatriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
