# Generated by Django 4.2 on 2024-07-16 09:32

import Vehicule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicule', '0005_vehicule_couleur_alter_vehicule_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_immatriculation',
            field=models.DateField(default=Vehicule.models.default_date_immatriculation),
        ),
    ]
