# Generated by Django 4.2 on 2024-07-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicule', '0007_alter_vehicule_marque_alter_vehicule_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='carburant',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique'), ('gaz', 'Gaz'), ('autre', 'Autre')], default='essence', max_length=20),
        ),
    ]
