# Generated by Django 4.2 on 2024-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('berline', 'Berline'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('crossover', 'Crossover'), ('coupe', 'Coupé'), ('cabriolet', 'Cabriolet'), ('break', 'Break'), ('monospace', 'Monospace'), ('pickup', 'Pick-up'), ('fourgon', 'Fourgon')], max_length=20, unique=True)),
            ],
        ),
    ]
