# Generated by Django 4.2 on 2024-07-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('permis_conduire_numero', models.CharField(max_length=20, unique=True)),
                ('permis_conduire_date_emission', models.DateField()),
                ('permis_conduire_date_expiration', models.DateField()),
                ('carte_sejour_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('carte_sejour_date_emission', models.DateField(blank=True, null=True)),
                ('cin_numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('niveau_risque', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
