# Generated by Django 4.2 on 2024-07-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conducteur', '0003_remove_conducteur_cin_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conducteur',
            old_name='carte_sejour_date_emission',
            new_name='date_de_naissance',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='lieu_naissance',
            new_name='lieu_de_naissance',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='date_naissance',
            new_name='passeport_date_emission',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='carte_sejour_numero',
            new_name='passeport_numero',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='permis_conduire_date_emission',
            new_name='permis_de_conduire_date_emission',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='permis_conduire_date_expiration',
            new_name='permis_de_conduire_date_expiration',
        ),
        migrations.RenameField(
            model_name='conducteur',
            old_name='permis_conduire_numero',
            new_name='permis_numero',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='conducteur',
            name='niveau_risque',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='copie_passeport',
            field=models.FileField(blank=True, null=True, upload_to='passeport/'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='copie_permis',
            field=models.FileField(blank=True, null=True, upload_to='permis/'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='est_chauffeur_interne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='nationalite',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='passeport_date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='pays',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conducteur',
            name='telephone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='ville',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
