# Generated by Django 4.2 on 2024-07-16 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paiement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='date',
        ),
    ]
